sudo: true
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

install:
  - "pip install -r requirements/requirements.txt"
  - "pip install coveralls"
# All before the actual tests
before_script:
  - sh ./scripts/ArangoDB/arangodb_startup.sh
# command to run tests
script:
  - coverage run --source=arangodb tests.py
  - coverage report
# Run after all finished correctly
after_success:
  coveralls
