language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements/requirements.txt"
# All before the actual tests
before_script:
  - sh ./scripts/ArangoDB/arangodb_startup.sh
# command to run tests
script: python tests.py